environment: "MountainCarContinuous-v0"
algorithm: "PPO"
timesteps: 300000
checkpoint_freq: 10000
num_trials: 3

step_penalty: 0.0005
pos_reward_weight: 1.0
vel_reward_weight: 0.5
goal_position: 0.45
